---

- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - { role: build_inventory }

- hosts: lab_hosts
  gather_facts: false

  roles:
    - { role: core_checks, when: workshop_type == 'rhel' or workshop_type == 'networking' }
