---

- name: slurp back SSH key
  slurp:
    src: "~/.ssh/aws-private.pem"
  register: sshkey

- name: Correct Workshop Credential
  tower_credential:
    name: "{{ tower_workshop_credential_name }}"
    organization: "{{ tower_default_org }}"
    inputs:
      username: ec2-user
      ssh_key_data: "{{ sshkey['content'] | b64decode }}"
    credential_type: Machine
    state: present
    tower_username: "{{ tower_username }}"
    tower_password: "{{ student_password }}"
    validate_certs: false
  delegate_to: "{{ inventory_hostname }}"

